#!/bin/bash

set -e

export GOPATH=${PWD}/gopath
export PATH=${PATH}:${GOPATH}/bin
cd ${GOPATH}/src/${MODULE}

mkdir -p ${GOPATH}/bin
go version; echo; echo
curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
dep ensure
go vet $(go list ./... | grep -v vendor)
go test -v ./...
